# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help make automated releases for this project

name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Use the provided GITHUB_TOKEN for HTTPS checkout in the runner
          # to avoid SSH publickey permission errors on GitHub-hosted runners.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Ensure tags and full history are available when the workflow needs to fetch tags
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: python3 -m pip install -U setuptools wheel build --user
      - name: Build
        run: python3 -m build .
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true